# Generated by Django 4.2.4 on 2023-08-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0002_alter_category_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
