# Generated by Django 4.2.4 on 2023-08-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0004_alter_ad_file_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
