# Generated by Django 4.2.4 on 2023-08-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0005_alter_ad_file_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
