# Generated by Django 4.2.4 on 2023-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0008_ad_video_alter_ad_file_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files_uploaded'),
        ),
    ]
